[package]
name = "datacake"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
datacake-crdt = { version = "0.3", path = "datacake-crdt" }
datacake-cluster = { version = "0.1", path = "datacake-cluster" }
datacake-sqlite = { version = "0.1", path = "datacake-sqlite" }

[features]
test-utils = ["datacake-cluster/test-utils"]
rkyv = ["datacake-crdt/rkyv-support"]

[workspace]
members = [
    "datacake-cluster",
    "datacake-crdt",
    "datacake-sqlite",

    # Example set
    "examples/replicated-kv",
]