[package]
name = "datacake"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[workspace]
members = [
    "datacake-cluster",
    "datacake-crdt",
    "examples/sled-cluster"
]