unstable_features = true
combine_control_expr = false
imports_layout = "HorizontalVertical"
match_block_trailing_comma = true
imports_granularity = "Module"
group_imports = "StdExternalCrate"
max_width = 89

ignore = [
    "datacake-eventual-consistency/src/rpc/chitchat_transport_api.rs.rs",
    "datacake-eventual-consistency/src/rpc/datacake_api.rs.rs",
]