[package]
name = "datacake-rpc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytecheck = "0.6.9"
quinn = "0.9.3"
anyhow = "1"
async-trait = "0.1.60"
thiserror = "1"
parking_lot = "0.12.1"
rcgen = "0.10.0"
tracing = "0.1.37"
socket2 = "0.4.7"

rustls = { version = "0.20", features = ["dangerous_configuration"] }
rkyv = { version = "0.7.39", features = ["validation"] }
tokio = { version = "1", default-features = false, features = ["rt"] }

[dev-dependencies]
tokio = { version = "1", features = ["full"] }

