name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        rust: [stable]

    steps:
      - name: Install cargo-hack
        run: cargo install cargo-hack
      - uses: Swatinem/rust-cache@v1
      - name: Check features
        run: cargo hack check --all --ignore-private --each-feature --no-dev-deps
      - name: Check all targets
        run: cargo check --all --all-targets --all-features

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        rust: [stable]

    steps:
      - uses: Swatinem/rust-cache@v1
      - name: Run main tests
        run: cargo test --all --all-features -j 4 --keep-going